// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anybrusiaumusdlnkhqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFueWJydXNpYXVtdXNkbG5raHFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNzM5ODgsImV4cCI6MjA1OTg0OTk4OH0.3ZDK5tUJswLyX6FvF0Rikl9ScFvGrlc2awtoCMA6-pk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);